### ISSUE TITLE
Collections support

### ISSUE THREAD

**Issue by kaithar** [git-no/jekyll-breadcrumbs#3]
I might be going at this wrong, but it says there's collections support but I got nothing.  I'm using a structure like this:

tree

```
_site
 +- _part_B
 |     +- page.md
 +- part_A
       +- index.html
```

``` yaml
# tail _config.yml
collections:
  part_b:
    output: true

# head _part_B/page.md

---
layout: page
title: Longer page title
breadcrumb: My Page
permalink: /part_A/part_B/page/

---
```

My goal is that the breadcrumbs displayed on the page mentioned should have something like `Start / part_A.index.crumb / part_B.index.crumb / part_B.page.crumb`
Essentially taking the document url and then trying to append a crumb for whatever document is at each of the path components.  This worked when the file resided at `/part_A/part_B/page.md` just fine, but in trying to convert to using collections it has broken and I can't seem to figure out why.

Am I missing something obvious?  Is this not possible?
